# Generated by Django 6.0.1 on 2026-01-31 14:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('substation_id', models.CharField(help_text='Combination of mnemonic and voltage (e.g., ABBA132)', max_length=100, primary_key=True, serialize=False)),
                ('mnemonic', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ownership', models.CharField(max_length=100)),
                ('voltage', models.DecimalField(decimal_places=2, help_text='Voltage in kV', max_digits=10)),
                ('sld', models.CharField(help_text='Generated as {substation_id}.pdf', max_length=255)),
                ('sld_file', models.FileField(blank=True, help_text='Upload PDF or Image SLD', null=True, upload_to=core.models.substation_sld_path)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Substation',
                'verbose_name_plural': 'Substations',
                'ordering': ['substation_id'],
            },
        ),
    ]
