# Generated by Django 6.0.1 on 2026-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='grid',
            field=models.CharField(blank=True, choices=[('KEDP', 'KEDP'), ('PPNG', 'PPNG'), ('PERK', 'PERK'), ('SELG', 'SELG'), ('KLUM', 'KLUM'), ('NSEM', 'NSEM'), ('MLKA', 'MLKA'), ('JOH2', 'JOH2'), ('JOH1', 'JOH1'), ('PHNG', 'PHNG'), ('TERG', 'TERG'), ('KELN', 'KELN')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='substation',
            name='mnemonic',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='substation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='substation',
            name='ownership',
            field=models.CharField(choices=[('TNB', 'Tenaga Nasional Berhad (TNB)'), ('DC', 'Data Centre (DC)'), ('LSS', 'Large Scale Solar (LSS)'), ('IPP', 'Independent Power Producer (IPP)')], default='TNB', max_length=50),
        ),
        migrations.AlterField(
            model_name='substation',
            name='substation_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='substation',
            name='voltage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
