# Generated by Django 6.0.1 on 2026-01-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_substation_grid_substation_region_substation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='voltage',
            field=models.IntegerField(choices=[(500, '500 kV'), (275, '275 kV'), (132, '132 kV')]),
        ),
    ]
