# Generated by Django 6.0.1 on 2026-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_substation_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='geocoding_accuracy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='substation',
            name='sync_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
