# Generated by Django 6.0.1 on 2026-01-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_substation_geocoding_accuracy_substation_sync_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substation',
            name='geocoding_accuracy',
        ),
    ]
