# Generated by Django 6.0.1 on 2026-02-02 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_substation_geocoding_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_id', models.CharField(max_length=50)),
                ('feeder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage', models.IntegerField(blank=True, null=True)),
                ('breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_bays', to='core.substation')),
            ],
            options={
                'unique_together': {('substation', 'bay_id')},
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer_id', models.CharField(max_length=20)),
                ('transformer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('hv_voltage', models.IntegerField(blank=True, null=True)),
                ('lv_voltage', models.IntegerField(blank=True, null=True)),
                ('capacity_mva', models.FloatField(blank=True, null=True)),
                ('hv_breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('lv_breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='core.substation')),
            ],
            options={
                'unique_together': {('substation', 'transformer_id')},
            },
        ),
    ]
