# Generated by Django 6.0.1 on 2026-02-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incomingbay_transformer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomingbay',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='transformer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='incomingbay',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('substation', 'bay_id'), name='uniq_active_incomingbay_per_substation'),
        ),
        migrations.AddConstraint(
            model_name='transformer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('substation', 'transformer_id'), name='uniq_active_transformer_per_substation'),
        ),
    ]
