# Generated by Django 6.0.1 on 2026-02-02 13:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_substation_commission_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incomingbay',
            name='uniq_active_incomingbay_per_substation',
        ),
        migrations.RemoveConstraint(
            model_name='transformer',
            name='uniq_active_transformer_per_substation',
        ),
        migrations.AlterField(
            model_name='substation',
            name='sld_file',
            field=models.FileField(blank=True, help_text='Upload PDF or Image SLD', null=True, storage=core.models.OverwriteStorage(), upload_to=core.models.substation_sld_path),
        ),
    ]
