# Generated by Django 6.0.1 on 2026-02-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_incomingbay_uniq_active_incomingbay_per_substation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingbay',
            name='bay_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='transformer_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
