# Generated by Django 6.0.1 on 2026-02-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_incomingbay_bay_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='transformer_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingbay',
            name='bay_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='incomingbay',
            name='feeder_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transformer',
            name='transformer_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
