# Generated by Django 6.0.1 on 2026-02-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transformer_transformer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingbay',
            old_name='feeder_name',
            new_name='bay_name',
        ),
        migrations.RenameField(
            model_name='transformer',
            old_name='transformer_id',
            new_name='bay_id',
        ),
        migrations.RenameField(
            model_name='transformer',
            old_name='transformer_name',
            new_name='bay_name',
        ),
    ]
