# Generated by Django 6.0.1 on 2026-02-03 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_feeder_name_incomingbay_bay_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BayLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pload_mw', models.FloatField(help_text='Active power load in MW')),
                ('qload_mvar', models.FloatField(help_text='Reactive power load in Mvar')),
                ('bus_name', models.CharField(max_length=100)),
                ('mnemonic', models.CharField(max_length=10)),
                ('bay_identifier', models.CharField(help_text='T1, T2, F1, etc.', max_length=20)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('upload_batch_id', models.UUIDField(default=uuid.uuid4, help_text='Groups rows from same upload')),
                ('matched', models.BooleanField(default=False, help_text='Successfully matched to bay_id')),
                ('incoming_bay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_data', to='core.incomingbay')),
                ('transformer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_data', to='core.transformer')),
            ],
            options={
                'indexes': [models.Index(fields=['upload_batch_id'], name='core_bayloa_upload__d8a92a_idx'), models.Index(fields=['matched'], name='core_bayloa_matched_ce0095_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('transformer__isnull', False), ('incoming_bay__isnull', False), _connector='OR'), name='either_transformer_or_bay')],
            },
        ),
    ]
