# Generated by Django 6.0.1 on 2026-02-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bayload'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bayload',
            name='either_transformer_or_bay',
        ),
    ]
