# Generated by Django 6.0.1 on 2026-02-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_bayload_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='ownership',
            field=models.CharField(choices=[('TNB', 'Tenaga Nasional Berhad (TNB)'), ('DC', 'Data Centre (DC)'), ('LSS', 'Large Scale Solar (LSS)'), ('IPP', 'Independent Power Producer (IPP)'), ('LPC', 'Large Power Consumer (LPC)')], default='TNB', max_length=50),
        ),
    ]
