# Generated by Django 6.0.1 on 2026-02-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_lpc_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayload',
            name='incoming_bay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_data', to='core.incomingbay'),
        ),
        migrations.AlterField(
            model_name='bayload',
            name='transformer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_data', to='core.transformer'),
        ),
    ]
