# Generated by Django 6.0.2 on 2026-02-08 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_bayload_incoming_bay_alter_bayload_transformer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingbay',
            options={'verbose_name': 'Incoming Bay', 'verbose_name_plural': 'Incoming Bays'},
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='auto_detected',
            field=models.BooleanField(default=False, help_text='True if connection was auto-detected'),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='connected_to_substation',
            field=models.ForeignKey(blank=True, help_text='Primary connected substation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_from_bays', to='core.substation'),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='connection_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Connection'), ('TEE_OFF', 'Tee-Off Connection'), ('AUTOTRANSFORMER', 'Autotransformer'), ('EQUIPMENT', 'Equipment (Not a connection)'), ('UNKNOWN', 'Unknown/Unvalidated')], default='UNKNOWN', help_text='Type of connection detected', max_length=20),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='detection_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score 0.0-1.0 for auto-detection', null=True),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='detection_note',
            field=models.TextField(blank=True, help_text='Explanation of detection logic or issues', null=True),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='tee_off_connections',
            field=models.ManyToManyField(blank=True, help_text='Additional substations for tee-off connections', related_name='tee_off_bays', to='core.substation'),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='topology_changed',
            field=models.BooleanField(default=False, help_text='True if bay name changed since last validation'),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='topology_last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time topology was checked', null=True),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='When the connection was validated', null=True),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='User who validated this connection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_topology_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomingbay',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALIDATED', 'User Validated'), ('AUTO_VALIDATED', 'Auto-Validated (High Confidence)'), ('REJECTED', 'Rejected/Needs Review')], default='PENDING', help_text='Validation status of the connection', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incomingbay',
            index=models.Index(fields=['validation_status'], name='core_incomi_validat_108189_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingbay',
            index=models.Index(fields=['connection_type'], name='core_incomi_connect_2aebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingbay',
            index=models.Index(fields=['detection_confidence'], name='core_incomi_detecti_af94a5_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingbay',
            index=models.Index(fields=['substation', 'validation_status'], name='core_incomi_substat_0ef06c_idx'),
        ),
    ]
