# Generated by Django 6.0.1 on 2026-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_network_topology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingbay',
            name='breaker_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='hv_breaker_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='lv_breaker_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='lv_voltage',
            field=models.IntegerField(default=0),
        ),
    ]
