# Generated by Django 6.0.1 on 2026-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_incomingbay_breaker_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='connection_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Connection'), ('TEE_OFF', 'Tee-Off Connection'), ('AUTOTRANSFORMER', 'Autotransformer'), ('EQUIPMENT', 'Equipment (Not a connection)'), ('UNKNOWN', 'Unknown/Unvalidated')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='capacity_mva',
            field=models.FloatField(blank=True, help_text='Transformer capacity in MVA', null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='hv_breaker_number',
            field=models.CharField(blank=True, help_text='HV Breaker ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='hv_voltage',
            field=models.FloatField(blank=True, help_text='High voltage side kV', null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='lv_breaker_number',
            field=models.CharField(blank=True, help_text='LV Breaker ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='lv_voltage',
            field=models.FloatField(blank=True, help_text='Low voltage side kV', null=True),
        ),
    ]
