# Generated by Django 6.0.1 on 2026-02-12 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_transformer_connection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt_id', models.CharField(default='1', max_length=2)),
                ('r', models.FloatField(help_text='Resistance (pu)')),
                ('x', models.FloatField(help_text='Reactance (pu)')),
                ('b', models.FloatField(help_text='Charging (pu)')),
                ('rate_a', models.FloatField(default=0.0)),
                ('rate_b', models.FloatField(default=0.0)),
                ('rate_c', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.IntegerField(db_index=True)),
                ('bus_name', models.CharField(max_length=20)),
                ('base_kv', models.FloatField(db_index=True)),
                ('voltage_mag', models.FloatField(help_text='Voltage Magnitude (pu)')),
                ('voltage_angle', models.FloatField(help_text='Voltage Angle (degrees)')),
                ('nv_hi', models.FloatField(blank=True, null=True)),
                ('nv_lo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDCLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rectifier_bus_number', models.IntegerField()),
                ('inverter_bus_number', models.IntegerField()),
                ('setpoint_mw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_id', models.CharField(max_length=2)),
                ('p_gen', models.FloatField()),
                ('q_gen', models.FloatField()),
                ('p_max', models.FloatField()),
                ('p_min', models.FloatField()),
                ('q_max', models.FloatField()),
                ('q_min', models.FloatField()),
                ('in_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=2)),
                ('p_mw', models.FloatField()),
                ('q_mvar', models.FloatField()),
                ('in_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkShunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shunt_id', models.CharField(max_length=2)),
                ('g_mw', models.FloatField(help_text='Shunt Conductance')),
                ('b_mvar', models.FloatField(help_text='Shunt Susceptance')),
                ('in_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Feb 2026 Forecast'", max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('base_mva', models.FloatField(default=100.0)),
                ('frequency', models.FloatField(default=50.0)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='snapshots/')),
            ],
            options={
                'verbose_name': 'Network Snapshot',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSwitchedShunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_mode', models.IntegerField()),
                ('b_init', models.FloatField()),
                ('step_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt_id', models.CharField(default='1', max_length=2)),
                ('r', models.FloatField(default=0.0)),
                ('x', models.FloatField()),
                ('primary_winding', models.IntegerField(default=1)),
                ('rate_a', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='bayload',
            name='core_bayloa_upload__d8a92a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bayload',
            name='core_bayloa_matched_ce0095_idx',
        ),
        migrations.RemoveIndex(
            model_name='incomingbay',
            name='core_incomi_validat_108189_idx',
        ),
        migrations.RemoveIndex(
            model_name='incomingbay',
            name='core_incomi_connect_2aebf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='incomingbay',
            name='core_incomi_detecti_af94a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='incomingbay',
            name='core_incomi_substat_0ef06c_idx',
        ),
        migrations.RemoveField(
            model_name='transformer',
            name='substation',
        ),
        migrations.AlterModelOptions(
            name='substation',
            options={'ordering': ['substation_id'], 'verbose_name': 'Substation (Master)', 'verbose_name_plural': 'Substations (Master)'},
        ),
        migrations.AlterField(
            model_name='substation',
            name='mnemonic',
            field=models.CharField(help_text='Unique identifier for matching (e.g. SDAO)', max_length=10),
        ),
        migrations.AddField(
            model_name='networkbus',
            name='psse_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.networkarea'),
        ),
        migrations.AddField(
            model_name='networkbus',
            name='substation',
            field=models.ForeignKey(blank=True, help_text='Linked Master Substation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_buses', to='core.substation'),
        ),
        migrations.AddField(
            model_name='networkbranch',
            name='from_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches_from', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkbranch',
            name='to_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches_to', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkgenerator',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkload',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkbus',
            name='psse_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.networkowner'),
        ),
        migrations.AddField(
            model_name='networkshunt',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shunts', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkshunt',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shunts', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkowner',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkload',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkgenerator',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkdclink',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_links', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkbus',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkbranch',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkarea',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkswitchedshunt',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switched_shunts', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkswitchedshunt',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switched_shunts', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='from_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers_from', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='to_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers_to', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networkzone',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='networkbus',
            name='psse_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.networkzone'),
        ),
        migrations.RemoveField(
            model_name='bayload',
            name='incoming_bay',
        ),
        migrations.RemoveField(
            model_name='bayload',
            name='transformer',
        ),
        migrations.RemoveField(
            model_name='incomingbay',
            name='connected_to_substation',
        ),
        migrations.RemoveField(
            model_name='incomingbay',
            name='substation',
        ),
        migrations.RemoveField(
            model_name='incomingbay',
            name='tee_off_connections',
        ),
        migrations.RemoveField(
            model_name='incomingbay',
            name='validated_by',
        ),
        migrations.AlterUniqueTogether(
            name='networkowner',
            unique_together={('snapshot', 'number')},
        ),
        migrations.AddIndex(
            model_name='networkbranch',
            index=models.Index(fields=['snapshot', 'from_bus', 'to_bus'], name='core_networ_snapsho_0cefd0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='networkarea',
            unique_together={('snapshot', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='networkzone',
            unique_together={('snapshot', 'number')},
        ),
        migrations.AddIndex(
            model_name='networkbus',
            index=models.Index(fields=['snapshot', 'bus_number'], name='core_networ_snapsho_1048bd_idx'),
        ),
        migrations.AddIndex(
            model_name='networkbus',
            index=models.Index(fields=['snapshot', 'substation'], name='core_networ_snapsho_c7926e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='networkbus',
            unique_together={('snapshot', 'bus_number')},
        ),
        migrations.DeleteModel(
            name='BayLoad',
        ),
        migrations.DeleteModel(
            name='Transformer',
        ),
        migrations.DeleteModel(
            name='IncomingBay',
        ),
    ]
