# Generated by Django 6.0.1 on 2026-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_networkarea_networkbranch_networkbus_networkdclink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkarea',
            options={'verbose_name': 'Network Area', 'verbose_name_plural': 'Network Areas'},
        ),
        migrations.AlterModelOptions(
            name='networkowner',
            options={'verbose_name': 'Network Owner', 'verbose_name_plural': 'Network Owners'},
        ),
        migrations.AlterModelOptions(
            name='networkzone',
            options={'verbose_name': 'Network Zone', 'verbose_name_plural': 'Network Zones'},
        ),
        migrations.AddField(
            model_name='networksnapshot',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Import metadata including unmatched mnemonics'),
        ),
    ]
