# Generated by Django 6.0.1 on 2026-02-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_snapshot_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktransformer',
            name='nomv1',
            field=models.FloatField(default=0.0, help_text='Winding 1 nominal voltage (kV)'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='nomv2',
            field=models.FloatField(default=0.0, help_text='Winding 2 nominal voltage (kV)'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='nomv3',
            field=models.FloatField(blank=True, help_text='Winding 3 nominal voltage (kV)', null=True),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='tertiary_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformers_tertiary', to='core.networkbus'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='windv1',
            field=models.FloatField(default=1.0, help_text='Winding 1 ratio/voltage'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='windv2',
            field=models.FloatField(default=1.0, help_text='Winding 2 ratio/voltage'),
        ),
        migrations.AddField(
            model_name='networktransformer',
            name='windv3',
            field=models.FloatField(blank=True, help_text='Winding 3 ratio/voltage', null=True),
        ),
        migrations.AddIndex(
            model_name='networktransformer',
            index=models.Index(fields=['snapshot', 'from_bus', 'to_bus'], name='core_networ_snapsho_c4ea8a_idx'),
        ),
    ]
