# Generated by Django 6.0.1 on 2026-02-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_networktransformer_nomv1_networktransformer_nomv2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substation',
            name='sync_log',
        ),
    ]
