# Generated by Django on 2026-02-18 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_networksnapshot_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkbus',
            name='bus_type',
            field=models.IntegerField(default=1, help_text='PSS/E IDE Code (1=Load, 2=Gen, 3=Swing, 4=Isolated)'),
        ),
    ]
