# Generated by Django 6.0.1 on 2026-02-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_networkbus_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksnapshot',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networksnapshot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
