# Generated by Django 6.0.1 on 2026-02-20 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_snapshot_topology(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    NetworkTopology = apps.get_model('core', 'NetworkTopology')
    TopologyVersion = apps.get_model('core', 'TopologyVersion')
    TopologyBus = apps.get_model('core', 'TopologyBus')
    TopologyBranch = apps.get_model('core', 'TopologyBranch')
    TopologyTransformer = apps.get_model('core', 'TopologyTransformer')
    SnapshotBusState = apps.get_model('core', 'SnapshotBusState')
    NetworkSnapshot = apps.get_model('core', 'NetworkSnapshot')
    NetworkBus = apps.get_model('core', 'NetworkBus')
    NetworkBranch = apps.get_model('core', 'NetworkBranch')
    NetworkTransformer = apps.get_model('core', 'NetworkTransformer')

    topology, _ = NetworkTopology.objects.using(db_alias).get_or_create(name='National Topology')

    for snapshot in NetworkSnapshot.objects.using(db_alias).all():
        version = TopologyVersion.objects.using(db_alias).create(
            topology_id=topology.id,
            version_tag=snapshot.timestamp.strftime('%Y-%m-%d'),
            signature=f"migrated-{snapshot.id}",
            created_from_snapshot_id=snapshot.id,
        )

        buses = []
        states = []
        for bus in NetworkBus.objects.using(db_alias).filter(snapshot_id=snapshot.id).iterator():
            buses.append(TopologyBus(
                id=bus.id,
                topology_version_id=version.id,
                substation_id=bus.substation_id,
                bus_number=bus.bus_number,
                bus_name=bus.bus_name,
                base_kv=bus.base_kv,
                psse_area=bus.psse_area.number if bus.psse_area_id else None,
                psse_zone=bus.psse_zone.number if bus.psse_zone_id else None,
                psse_owner=bus.psse_owner.number if bus.psse_owner_id else None,
            ))
            states.append(SnapshotBusState(
                snapshot_id=snapshot.id,
                bus_id=bus.id,
                bus_type=bus.bus_type,
                voltage_mag=bus.voltage_mag,
                voltage_angle=bus.voltage_angle,
                nv_hi=bus.nv_hi,
                nv_lo=bus.nv_lo,
            ))

        if buses:
            TopologyBus.objects.using(db_alias).bulk_create(buses, batch_size=1000)
        if states:
            SnapshotBusState.objects.using(db_alias).bulk_create(states, batch_size=1000)

        branches = []
        for br in NetworkBranch.objects.using(db_alias).filter(snapshot_id=snapshot.id).iterator():
            branches.append(TopologyBranch(
                id=br.id,
                topology_version_id=version.id,
                from_bus_id=br.from_bus_id,
                to_bus_id=br.to_bus_id,
                ckt_id=br.ckt_id,
                r=br.r,
                x=br.x,
                b=br.b,
                rate_a=br.rate_a,
                rate_b=br.rate_b,
                rate_c=br.rate_c,
                is_active=br.is_active,
            ))
        if branches:
            TopologyBranch.objects.using(db_alias).bulk_create(branches, batch_size=1000)

        transformers = []
        for tx in NetworkTransformer.objects.using(db_alias).filter(snapshot_id=snapshot.id).iterator():
            transformers.append(TopologyTransformer(
                id=tx.id,
                topology_version_id=version.id,
                from_bus_id=tx.from_bus_id,
                to_bus_id=tx.to_bus_id,
                tertiary_bus_id=tx.tertiary_bus_id,
                ckt_id=tx.ckt_id,
                r=tx.r,
                x=tx.x,
                primary_winding=tx.primary_winding,
                windv1=tx.windv1,
                windv2=tx.windv2,
                windv3=tx.windv3,
                nomv1=tx.nomv1,
                nomv2=tx.nomv2,
                nomv3=tx.nomv3,
                rate_a=tx.rate_a,
                is_active=tx.is_active,
            ))
        if transformers:
            TopologyTransformer.objects.using(db_alias).bulk_create(transformers, batch_size=1000)

        NetworkSnapshot.objects.using(db_alias).filter(id=snapshot.id).update(
            topology_version_id=version.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_relay_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTopology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='National Topology', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelayTripAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('branch', 'Branch (Feeder / Interconnector)'), ('load_transformer', 'Load Transformer')], max_length=20)),
                ('target_substation_id', models.CharField(blank=True, help_text='Remote-end substation for branch assignments', max_length=20, null=True)),
                ('circuit_id', models.CharField(help_text="e.g. '1', '2' for feeders; 'T1', 'T2' for transformers", max_length=10)),
            ],
            options={
                'ordering': ['relay', 'assignment_type', 'target_substation_id', 'circuit_id'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotBusState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.IntegerField(default=1, help_text='PSS/E IDE Code (1=Load, 2=Gen, 3=Swing, 4=Isolated)')),
                ('voltage_mag', models.FloatField(help_text='Voltage Magnitude (pu)')),
                ('voltage_angle', models.FloatField(help_text='Voltage Angle (degrees)')),
                ('nv_hi', models.FloatField(blank=True, null=True)),
                ('nv_lo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt_id', models.CharField(default='1', max_length=2)),
                ('r', models.FloatField(help_text='Resistance (pu)')),
                ('x', models.FloatField(help_text='Reactance (pu)')),
                ('b', models.FloatField(help_text='Charging (pu)')),
                ('rate_a', models.FloatField(default=0.0)),
                ('rate_b', models.FloatField(default=0.0)),
                ('rate_c', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.IntegerField(db_index=True)),
                ('bus_name', models.CharField(max_length=20)),
                ('base_kv', models.FloatField(db_index=True)),
                ('psse_area', models.IntegerField(blank=True, null=True)),
                ('psse_zone', models.IntegerField(blank=True, null=True)),
                ('psse_owner', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt_id', models.CharField(default='1', max_length=2)),
                ('r', models.FloatField(default=0.0)),
                ('x', models.FloatField()),
                ('primary_winding', models.IntegerField(default=1)),
                ('windv1', models.FloatField(default=1.0)),
                ('windv2', models.FloatField(default=1.0)),
                ('windv3', models.FloatField(blank=True, null=True)),
                ('nomv1', models.FloatField(default=0.0)),
                ('nomv2', models.FloatField(default=0.0)),
                ('nomv3', models.FloatField(blank=True, null=True)),
                ('rate_a', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopologyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='networkbranch',
            name='core_networ_snapsho_0cefd0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='networkbus',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='networkbus',
            name='core_networ_snapsho_1048bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='networkbus',
            name='core_networ_snapsho_c7926e_idx',
        ),
        migrations.RemoveIndex(
            model_name='networktransformer',
            name='core_networ_snapsho_c4ea8a_idx',
        ),
        migrations.AlterModelOptions(
            name='loadsheddingscheme',
            options={'ordering': ['scheme_type']},
        ),
        migrations.AlterModelOptions(
            name='schemeversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shedgroupassignment',
            options={'ordering': ['group', 'relay_trip']},
        ),
        migrations.AlterModelOptions(
            name='shedgroupsetting',
            options={'ordering': ['version', 'operating_stage']},
        ),
        migrations.RemoveConstraint(
            model_name='schemeversion',
            name='unique_version_per_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='shedgroupsetting',
            name='unique_operating_stage_per_version',
        ),
        migrations.RemoveField(
            model_name='protectionrelay',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='protectionrelay',
            name='circuit_id',
        ),
        migrations.RemoveField(
            model_name='protectionrelay',
            name='from_substation_id',
        ),
        migrations.RemoveField(
            model_name='protectionrelay',
            name='to_substation_id',
        ),
        migrations.RemoveField(
            model_name='shedgroupassignment',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='shedgroupassignment',
            name='circuit_id',
        ),
        migrations.RemoveField(
            model_name='shedgroupassignment',
            name='from_substation_id',
        ),
        migrations.RemoveField(
            model_name='shedgroupassignment',
            name='substation',
        ),
        migrations.RemoveField(
            model_name='shedgroupassignment',
            name='to_substation_id',
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('core', 'ShedGroupAssignment').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='networksnapshot',
            name='import_type',
            field=models.CharField(choices=[('RAW_FULL', 'Full RAW Import'), ('LOAD_PROFILE_ONLY', 'Load Profile Only')], default='RAW_FULL', max_length=30),
        ),
        migrations.AddField(
            model_name='protectionrelay',
            name='relay_panel_location',
            field=models.CharField(blank=True, help_text="e.g. '132kV Coupler', 'Bay 3 Panel'", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loadsheddingscheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loadsheddingscheme',
            name='name',
            field=models.CharField(help_text='e.g. "National UFLS Scheme"', max_length=100),
        ),
        migrations.AlterField(
            model_name='schemeversion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemeversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shedgroupsetting',
            name='operating_stage',
            field=models.PositiveSmallIntegerField(help_text='Stage number; 1 = shed first'),
        ),
        migrations.AlterField(
            model_name='shedgroupsetting',
            name='target_mw_shed',
            field=models.FloatField(blank=True, help_text='Planned MW quantum', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='shedgroupsetting',
            unique_together={('version', 'operating_stage')},
        ),
        migrations.AddField(
            model_name='relaytripassignment',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_assignments', to='core.protectionrelay'),
        ),
        migrations.AddField(
            model_name='shedgroupassignment',
            name='relay_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='core.relaytripassignment'),
        ),
        migrations.AddField(
            model_name='snapshotbusstate',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_states', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='topologybus',
            name='substation',
            field=models.ForeignKey(blank=True, help_text='Linked Master Substation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topology_buses', to='core.substation'),
        ),
        migrations.AddField(
            model_name='topologybranch',
            name='from_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches_from', to='core.topologybus'),
        ),
        migrations.AddField(
            model_name='topologybranch',
            name='to_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches_to', to='core.topologybus'),
        ),
        migrations.AddField(
            model_name='snapshotbusstate',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.topologybus'),
        ),
        migrations.AddField(
            model_name='topologytransformer',
            name='from_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers_from', to='core.topologybus'),
        ),
        migrations.AddField(
            model_name='topologytransformer',
            name='tertiary_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transformers_tertiary', to='core.topologybus'),
        ),
        migrations.AddField(
            model_name='topologytransformer',
            name='to_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers_to', to='core.topologybus'),
        ),
        migrations.AddField(
            model_name='topologyversion',
            name='created_from_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topology_versions', to='core.networksnapshot'),
        ),
        migrations.AddField(
            model_name='topologyversion',
            name='topology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.networktopology'),
        ),
        migrations.AddField(
            model_name='topologytransformer',
            name='topology_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='core.topologyversion'),
        ),
        migrations.AddField(
            model_name='topologybus',
            name='topology_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.topologyversion'),
        ),
        migrations.AddField(
            model_name='topologybranch',
            name='topology_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.topologyversion'),
        ),
        migrations.AddField(
            model_name='networksnapshot',
            name='topology_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='core.topologyversion'),
        ),
        migrations.AddField(
            model_name='schemeversion',
            name='topology_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_versions', to='core.topologyversion'),
        ),
        migrations.RunPython(migrate_snapshot_topology, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='networkgenerator',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='core.topologybus'),
        ),
        migrations.AlterField(
            model_name='networkload',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='core.topologybus'),
        ),
        migrations.AlterField(
            model_name='networkshunt',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shunts', to='core.topologybus'),
        ),
        migrations.AlterField(
            model_name='networkswitchedshunt',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switched_shunts', to='core.topologybus'),
        ),
        migrations.RemoveField(
            model_name='networkbranch',
            name='from_bus',
        ),
        migrations.RemoveField(
            model_name='networkbranch',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='networkbranch',
            name='to_bus',
        ),
        migrations.RemoveField(
            model_name='networkbus',
            name='psse_area',
        ),
        migrations.RemoveField(
            model_name='networkbus',
            name='psse_owner',
        ),
        migrations.RemoveField(
            model_name='networkbus',
            name='psse_zone',
        ),
        migrations.RemoveField(
            model_name='networkbus',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='networkbus',
            name='substation',
        ),
        migrations.RemoveField(
            model_name='networktransformer',
            name='from_bus',
        ),
        migrations.RemoveField(
            model_name='networktransformer',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='networktransformer',
            name='tertiary_bus',
        ),
        migrations.RemoveField(
            model_name='networktransformer',
            name='to_bus',
        ),
        migrations.AlterUniqueTogether(
            name='relaytripassignment',
            unique_together={('relay', 'assignment_type', 'target_substation_id', 'circuit_id')},
        ),
        migrations.AddIndex(
            model_name='snapshotbusstate',
            index=models.Index(fields=['snapshot', 'bus'], name='core_snapsh_snapsho_6a9719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshotbusstate',
            unique_together={('snapshot', 'bus')},
        ),
        migrations.AddIndex(
            model_name='topologytransformer',
            index=models.Index(fields=['topology_version', 'from_bus', 'to_bus'], name='core_topolo_topolog_410e90_idx'),
        ),
        migrations.AddIndex(
            model_name='topologybus',
            index=models.Index(fields=['topology_version', 'bus_number'], name='core_topolo_topolog_de0353_idx'),
        ),
        migrations.AddIndex(
            model_name='topologybus',
            index=models.Index(fields=['topology_version', 'substation'], name='core_topolo_topolog_8be197_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topologybus',
            unique_together={('topology_version', 'bus_number')},
        ),
        migrations.AddIndex(
            model_name='topologybranch',
            index=models.Index(fields=['topology_version', 'from_bus', 'to_bus'], name='core_topolo_topolog_d87482_idx'),
        ),
        migrations.DeleteModel(
            name='NetworkBranch',
        ),
        migrations.DeleteModel(
            name='NetworkBus',
        ),
        migrations.DeleteModel(
            name='NetworkTransformer',
        ),
    ]
