# Generated by OpenCode to enforce non-null relay_trip

from django.db import migrations, models
import django.db.models.deletion


def delete_null_relay_trip(apps, schema_editor):
    ShedGroupAssignment = apps.get_model('core', 'ShedGroupAssignment')
    ShedGroupAssignment.objects.filter(relay_trip__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_networktopology_relaytripassignment_snapshotbusstate_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_null_relay_trip, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shedgroupassignment',
            name='relay_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='core.relaytripassignment'),
        ),
    ]
