# Generated by Django 6.0.1 on 2026-02-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_enforce_relay_trip_not_null'),
    ]

    operations = [
        migrations.DeleteModel('ShedGroupAssignment'),
        migrations.DeleteModel('ShedGroupSetting'),
        migrations.DeleteModel('SchemeVersion'),
        migrations.DeleteModel('RelayTripAssignment'),
        migrations.DeleteModel('LoadSheddingScheme'),
        migrations.DeleteModel('ProtectionRelay'),
    ]
