# Generated by Django 6.0.2 on 2026-02-22 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_schemeversion_scheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer_no', models.IntegerField()),
                ('bay_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('hv_voltage', models.IntegerField(blank=True, null=True)),
                ('hv_breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('lv_voltage', models.IntegerField()),
                ('lv_breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('capacity_mva', models.IntegerField(blank=True, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_transformers', to='core.substation')),
            ],
            options={
                'ordering': ['substation__substation_id', 'transformer_no'],
                'unique_together': {('substation', 'transformer_no')},
            },
        ),
        migrations.CreateModel(
            name='IncomingBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckt_id', models.CharField(max_length=2)),
                ('breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bay_id', models.CharField(blank=True, max_length=80, unique=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_branches', to='core.substation')),
                ('to_substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_from_branches', to='core.substation')),
            ],
            options={
                'ordering': ['substation__substation_id', 'to_substation__substation_id', 'ckt_id'],
                'unique_together': {('substation', 'to_substation', 'ckt_id')},
            },
        ),
        migrations.CreateModel(
            name='IncomingBranchAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_id', models.CharField(max_length=80, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('incoming_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.incomingbranch')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LoadTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformer_no', models.IntegerField()),
                ('bay_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('hv_voltage', models.IntegerField(blank=True, null=True)),
                ('hv_breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('lv_voltage', models.IntegerField(blank=True, null=True)),
                ('lv_breaker_number', models.CharField(blank=True, max_length=10, null=True)),
                ('capacity_mva', models.IntegerField(blank=True, null=True)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_transformers', to='core.substation')),
            ],
            options={
                'ordering': ['substation__substation_id', 'transformer_no'],
                'unique_together': {('substation', 'transformer_no')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentTopologyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('load_transformer', 'Load Transformer'), ('incoming_branch', 'Incoming Branch'), ('auto_transformer', 'Auto Transformer')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.autotransformer')),
                ('topology_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topologybranch')),
                ('topology_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topologytransformer')),
                ('topology_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_maps', to='core.topologyversion')),
                ('incoming_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.incomingbranch')),
                ('load_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loadtransformer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('load_transformer__isnull', False), ('incoming_branch__isnull', True), ('auto_transformer__isnull', True)), models.Q(('load_transformer__isnull', True), ('incoming_branch__isnull', False), ('auto_transformer__isnull', True)), models.Q(('load_transformer__isnull', True), ('incoming_branch__isnull', True), ('auto_transformer__isnull', False)), _connector='OR'), name='equipment_map_master_xor'), models.CheckConstraint(condition=models.Q(models.Q(('topology_transformer__isnull', False), ('topology_branch__isnull', True)), models.Q(('topology_transformer__isnull', True), ('topology_branch__isnull', False)), _connector='OR'), name='equipment_map_topology_xor'), models.UniqueConstraint(fields=('topology_version', 'equipment_type', 'load_transformer'), name='uniq_map_load_transformer'), models.UniqueConstraint(fields=('topology_version', 'equipment_type', 'incoming_branch'), name='uniq_map_incoming_branch'), models.UniqueConstraint(fields=('topology_version', 'equipment_type', 'auto_transformer'), name='uniq_map_auto_transformer')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSnapshotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('load_transformer', 'Load Transformer'), ('incoming_branch', 'Incoming Branch'), ('auto_transformer', 'Auto Transformer')], max_length=30)),
                ('in_service', models.BooleanField(default=True)),
                ('state_source', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.autotransformer')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_states', to='core.networksnapshot')),
                ('incoming_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.incomingbranch')),
                ('load_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loadtransformer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('load_transformer__isnull', False), ('incoming_branch__isnull', True), ('auto_transformer__isnull', True)), models.Q(('load_transformer__isnull', True), ('incoming_branch__isnull', False), ('auto_transformer__isnull', True)), models.Q(('load_transformer__isnull', True), ('incoming_branch__isnull', True), ('auto_transformer__isnull', False)), _connector='OR'), name='equipment_state_master_xor')],
            },
        ),
    ]
