# Generated by Django 6.0.2 on 2026-02-23 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_autotransformer_incomingbranch_incomingbranchalias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CriticalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_date', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='CriticalAssetTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bay_id', models.CharField(db_index=True, max_length=80)),
                ('severity_rank', models.IntegerField(blank=True, null=True)),
                ('is_inforce', models.BooleanField(default=True)),
                ('inforce_from', models.DateField(blank=True, null=True)),
                ('inforce_to', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_tags', to='core.substation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.criticalcategory')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='core.criticalsource')),
            ],
            options={
                'ordering': ['substation__substation_id', 'bay_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_inforce', True)), fields=('substation', 'bay_id', 'category'), name='uniq_active_critical_tag')],
            },
        ),
    ]
