# Generated by Django 6.0.2 on 2026-02-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_criticalcategory_criticalsource_criticalassettag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticalassettag',
            options={'ordering': ['substation__substation_id', 'load_transformer__bay_id']},
        ),
        migrations.RemoveConstraint(
            model_name='criticalassettag',
            name='uniq_active_critical_tag',
        ),
        migrations.AddField(
            model_name='criticalassettag',
            name='load_transformer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critical_tags', to='core.loadtransformer'),
        ),
        migrations.AddConstraint(
            model_name='criticalassettag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_inforce', True)), fields=('substation', 'load_transformer', 'category'), name='uniq_active_critical_tag'),
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='bay_id',
        ),
    ]
