# Generated by Django 6.0.2 on 2026-02-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_criticalassettag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalcategory',
            name='code',
        ),
        migrations.RenameField(
            model_name='criticalcategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.AlterModelOptions(
            name='criticalcategory',
            options={'ordering': ['category_name']},
        ),
    ]
