# Generated by Django 6.0.2 on 2026-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_criticalcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='criticalcategory',
            name='category_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
