# Generated by Django 6.0.2 on 2026-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_criticalcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalassettag',
            name='inforce_from',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='inforce_to',
        ),
        migrations.AddField(
            model_name='criticalassettag',
            name='short_text',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
