# Generated by Django 6.0.2 on 2026-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_criticalassettag_inforce_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalsource',
            name='url',
        ),
        migrations.AddField(
            model_name='criticalsource',
            name='source_file',
            field=models.FileField(blank=True, upload_to='critical_sources/'),
        ),
    ]
