# Generated by Django 6.0.1 on 2026-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_criticalsource_url_criticalsource_source_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticalassettag',
            old_name='short_text',
            new_name='asset',
        ),
    ]
