# Generated by Django 6.0.1 on 2026-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_short_text_criticalassettag_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalassettag',
            name='severity_rank',
        ),
        migrations.AddField(
            model_name='criticalassettag',
            name='sensitivity_impact',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True),
        ),
    ]
