# Generated by Django 6.0.1 on 2026-02-26 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_criticalassettag_severity_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.CharField(max_length=200)),
                ('sensitivity_impact', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('is_inforce', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='criticalassettag',
            name='uniq_active_critical_tag',
        ),
        migrations.AddField(
            model_name='criticalasset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.criticalcategory'),
        ),
        migrations.AddField(
            model_name='criticalasset',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.criticalsource'),
        ),
        migrations.AddField(
            model_name='criticalassettag',
            name='critical_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.criticalasset'),
        ),
        migrations.AddConstraint(
            model_name='criticalassettag',
            constraint=models.UniqueConstraint(fields=('substation', 'load_transformer', 'critical_asset'), name='uniq_active_critical_tag'),
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='is_inforce',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='sensitivity_impact',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='source',
        ),
    ]
