# Generated by Django 6.0.1 on 2026-02-26 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_criticalasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalSubstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['substation__substation_id', 'load_transformer__bay_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='criticalassettag',
            name='uniq_active_critical_tag',
        ),
        migrations.RemoveField(
            model_name='criticalsource',
            name='notes',
        ),
        migrations.AddField(
            model_name='criticalasset',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='criticalsubstation',
            name='critical_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substations', to='core.criticalasset'),
        ),
        migrations.AddField(
            model_name='criticalsubstation',
            name='load_transformer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critical_tags', to='core.loadtransformer'),
        ),
        migrations.AddField(
            model_name='criticalsubstation',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_tags', to='core.substation'),
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='critical_asset',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='load_transformer',
        ),
        migrations.RemoveField(
            model_name='criticalassettag',
            name='substation',
        ),
        migrations.AddConstraint(
            model_name='criticalsubstation',
            constraint=models.UniqueConstraint(fields=('substation', 'load_transformer', 'critical_asset'), name='uniq_active_critical_substation'),
        ),
        migrations.DeleteModel(
            name='CriticalAssetTag',
        ),
    ]
