# Generated by Django 6.0.1 on 2026-02-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_criticalsubstation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='criticalsubstation',
            name='uniq_active_critical_substation',
        ),
        migrations.AddField(
            model_name='criticalasset',
            name='load_transformers',
            field=models.ManyToManyField(blank=True, related_name='critical_assets', to='core.loadtransformer'),
        ),
        migrations.AddField(
            model_name='criticalasset',
            name='substation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critical_assets', to='core.substation'),
        ),
        migrations.DeleteModel(
            name='CriticalSubstation',
        ),
    ]
