# Generated by Django 6.0.1 on 2026-02-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_criticalsubstation_uniq_active_critical_substation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalasset',
            name='asset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='criticalcategory',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
