# Generated by Django 6.0.1 on 2026-02-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_criticalasset_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalcategory',
            name='description',
        ),
    ]
