# Generated by Django 6.0.1 on 2026-02-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_criticalcategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticalsource',
            options={'ordering': ['-issued_date']},
        ),
        migrations.RemoveField(
            model_name='criticalsource',
            name='reference',
        ),
    ]
