# Generated by Django 6.0.2 on 2026-02-28 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_criticalsource_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheddingRelay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_shedding_relays', to='core.substation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoadSheddingRelayBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('load_transformer', 'Load Transformer'), ('incoming_branch', 'Circuit (Line/Cable)'), ('auto_transformer', 'Auto Transformer')], max_length=30)),
                ('auto_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.autotransformer')),
                ('incoming_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.incomingbranch')),
                ('load_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loadtransformer')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='core.loadsheddingrelay')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('load_transformer__isnull', False), ('incoming_branch__isnull', True), ('auto_transformer__isnull', True)), models.Q(('load_transformer__isnull', True), ('incoming_branch__isnull', False), ('auto_transformer__isnull', True)), models.Q(('load_transformer__isnull', True), ('incoming_branch__isnull', True), ('auto_transformer__isnull', False)), _connector='OR'), name='load_shedding_relay_bay_xor'), models.UniqueConstraint(fields=('relay', 'load_transformer'), name='uniq_relay_load_transformer'), models.UniqueConstraint(fields=('relay', 'incoming_branch'), name='uniq_relay_incoming_branch'), models.UniqueConstraint(fields=('relay', 'auto_transformer'), name='uniq_relay_auto_transformer'), models.UniqueConstraint(fields=('load_transformer',), name='uniq_load_transformer_relay'), models.UniqueConstraint(fields=('incoming_branch',), name='uniq_incoming_branch_relay'), models.UniqueConstraint(fields=('auto_transformer',), name='uniq_auto_transformer_relay')],
            },
        ),
    ]
