# Generated by Django 6.0.2 on 2026-02-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_loadsheddingrelay_loadsheddingrelaybay'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loadsheddingrelay',
            index=models.Index(fields=['substation'], name='core_loadsh_substat_94dcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='loadsheddingrelay',
            index=models.Index(fields=['is_active'], name='core_loadsh_is_acti_9c6743_idx'),
        ),
        migrations.AddIndex(
            model_name='loadsheddingrelaybay',
            index=models.Index(fields=['relay'], name='core_loadsh_relay_i_47f73c_idx'),
        ),
        migrations.AddIndex(
            model_name='loadsheddingrelaybay',
            index=models.Index(fields=['asset_type'], name='core_loadsh_asset_t_54be8a_idx'),
        ),
    ]
