# Generated by Django 6.0.2 on 2026-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_loadsheddingrelay_core_loadsh_substat_94dcd4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loadsheddingrelaybay',
            name='core_loadsh_relay_i_47f73c_idx',
        ),
        migrations.RemoveIndex(
            model_name='loadsheddingrelaybay',
            name='core_loadsh_asset_t_54be8a_idx',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='load_shedding_relay_bay_xor',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='uniq_relay_load_transformer',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='uniq_relay_incoming_branch',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='uniq_relay_auto_transformer',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='uniq_load_transformer_relay',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='uniq_incoming_branch_relay',
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingrelaybay',
            name='uniq_auto_transformer_relay',
        ),
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='auto_transformers',
            field=models.ManyToManyField(blank=True, related_name='load_shedding_relays', to='core.autotransformer'),
        ),
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='incoming_branches',
            field=models.ManyToManyField(blank=True, related_name='load_shedding_relays', to='core.incomingbranch'),
        ),
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='load_transformers',
            field=models.ManyToManyField(blank=True, related_name='load_shedding_relays', to='core.loadtransformer'),
        ),
        migrations.DeleteModel(
            name='LoadSheddingRelayBay',
        ),
    ]
