# Generated by Django 6.0.1 on 2026-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_loadsheddingrelaybay_core_loadsh_relay_i_47f73c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotransformer',
            name='hv_breaker_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomingbranch',
            name='breaker_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loadtransformer',
            name='hv_breaker_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
