# Generated by Django 6.0.1 on 2026-03-02 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_autotransformer_hv_breaker_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheddingStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('label', models.CharField(blank=True, help_text="e.g. 'Stage 9 — Sustained Underfrequency'", max_length=100, null=True)),
            ],
            options={
                'ordering': ['stage_number'],
            },
        ),
        migrations.CreateModel(
            name='LoadSheddingSpurBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topology_cache', models.JSONField(blank=True, help_text='{"snapshot_id": "...", "isolated_substations": [], "mw": 12.1, "computed_at": "..."}', null=True)),
                ('branches', models.ManyToManyField(related_name='load_shedding_spur_bays', to='core.incomingbranch')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_spur_bays', to='core.loadsheddingrelay')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spur_bays', to='core.loadsheddingstage')),
            ],
        ),
        migrations.CreateModel(
            name='LoadSheddingPocketBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topology_cache', models.JSONField(blank=True, help_text='{"snapshot_id": "...", "isolated_substations": [], "mw": 34.7, "computed_at": "..."}', null=True)),
                ('topology_valid', models.BooleanField(default=True)),
                ('topology_alert', models.TextField(blank=True, null=True)),
                ('boundary_branches', models.ManyToManyField(related_name='load_shedding_pocket_boundary_bays', to='core.incomingbranch')),
                ('boundary_relays', models.ManyToManyField(related_name='target_pocket_bays', to='core.loadsheddingrelay')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocket_bays', to='core.loadsheddingstage')),
            ],
        ),
        migrations.CreateModel(
            name='LoadSheddingTransformerBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mw_cache', models.JSONField(blank=True, help_text='{"snapshot_id": "...", "mw": 18.4, "computed_at": "..."}', null=True)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_transformer_bays', to='core.loadsheddingrelay')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_bays', to='core.loadsheddingstage')),
                ('transformers', models.ManyToManyField(related_name='load_shedding_transformer_bays', to='core.loadtransformer')),
            ],
        ),
        migrations.CreateModel(
            name='LoadSheddingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_type', models.CharField(choices=[('UFLS', 'Under-Frequency Load Shedding'), ('UVLS', 'Under-Voltage Load Shedding'), ('EMLS', 'Emergency Load Shedding')], max_length=10)),
                ('version_label', models.CharField(help_text="e.g. '2024-v1', '2025-draft'", max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently enforced version')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Change notes between versions')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_load_shedding_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Load Shedding Version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loadsheddingstage',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.loadsheddingversion'),
        ),
        migrations.CreateModel(
            name='LoadSheddingSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Stable sort key for multiple elements on the same stage')),
                ('threshold', models.FloatField(help_text='Hz for UFLS; p.u. for UVLS')),
                ('time_delay', models.FloatField(help_text='Seconds')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.loadsheddingstage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stage', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='loadsheddingstage',
            unique_together={('version', 'stage_number')},
        ),
    ]
