# Generated by Django 6.0.2 on 2026-03-03 09:15

from django.db import migrations, models


def forwards_add_m2m(apps, schema_editor):
    LoadSheddingVersion = apps.get_model('core', 'LoadSheddingVersion')
    LoadSheddingStage = apps.get_model('core', 'LoadSheddingStage')
    through_model = apps.get_model('core', 'LoadSheddingVersion_stages')

    for stage in LoadSheddingStage.objects.all():
        if stage.version_id:
            through_model.objects.get_or_create(
                loadsheddingversion_id=stage.version_id,
                loadsheddingstage_id=stage.id,
            )


def backwards_restore_fk(apps, schema_editor):
    LoadSheddingVersion = apps.get_model('core', 'LoadSheddingVersion')
    LoadSheddingStage = apps.get_model('core', 'LoadSheddingStage')
    through_model = apps.get_model('core', 'LoadSheddingVersion_stages')

    for stage in LoadSheddingStage.objects.all():
        link = through_model.objects.filter(loadsheddingstage_id=stage.id).first()
        if link:
            stage.version_id = link.loadsheddingversion_id
            stage.save(update_fields=['version'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_loadsheddingstage_loadsheddingspurbay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheddingversion',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='versions', to='core.loadsheddingstage'),
        ),
        migrations.RunPython(forwards_add_m2m, backwards_restore_fk),
        migrations.AlterUniqueTogether(
            name='loadsheddingstage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='loadsheddingstage',
            name='version',
        ),
    ]
