# Generated by Django 6.0.1 on 2026-03-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_loadsheddingversion_stages_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadsheddingversion',
            name='scheme_type',
            field=models.CharField(choices=[('UFLS', 'UFLS'), ('UVLS', 'UVLS'), ('UVLS', 'UVLS')], max_length=10),
        ),
    ]
