# Generated by Django 6.0.2 on 2026-03-03 12:10

from django.db import migrations, models


def reset_loadshedding_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    tables_to_drop = [
        'core_loadsheddingversion_stages',
        'core_loadsheddingtransformerbay_transformers',
        'core_loadsheddingtransformerbay',
        'core_loadsheddingspurbay_branches',
        'core_loadsheddingspurbay',
        'core_loadsheddingpocketbay_boundary_relays',
        'core_loadsheddingpocketbay_boundary_branches',
        'core_loadsheddingpocketbay',
        'core_loadsheddingstage',
        'core_loadsheddingversion',
        'core_loadsheddingsetting',
    ]

    for table_name in tables_to_drop:
        if table_name in existing_tables:
            schema_editor.execute(f"DROP TABLE IF EXISTS {table_name}")

    table_name = schema_editor.quote_name('core_loadsheddingsetting')
    if 'core_loadsheddingsetting' in existing_tables:
        schema_editor.execute(f"DROP TABLE IF EXISTS {table_name}")

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingsetting ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "scheme_type varchar(10) NOT NULL DEFAULT 'UFLS', "
        "threshold real NOT NULL, "
        "time_delay real NOT NULL, "
        "label varchar(64) NOT NULL DEFAULT ''"
        ")"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_loadsheddingversion_scheme_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(reset_loadshedding_tables, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterModelOptions(
                    name='loadsheddingsetting',
                    options={'ordering': ['scheme_type', 'threshold', 'time_delay']},
                ),
                migrations.AddField(
                    model_name='loadsheddingsetting',
                    name='label',
                    field=models.CharField(blank=True, editable=False, max_length=64),
                ),
                migrations.AddField(
                    model_name='loadsheddingsetting',
                    name='scheme_type',
                    field=models.CharField(choices=[('UFLS', 'UFLS'), ('UVLS', 'UVLS')], default='UFLS', max_length=10),
                ),
                migrations.RemoveField(
                    model_name='loadsheddingsetting',
                    name='order',
                ),
                migrations.RemoveField(
                    model_name='loadsheddingsetting',
                    name='stage',
                ),
                migrations.DeleteModel(
                    name='LoadSheddingTransformerBay',
                ),
                migrations.DeleteModel(
                    name='LoadSheddingSpurBay',
                ),
                migrations.DeleteModel(
                    name='LoadSheddingPocketBay',
                ),
                migrations.DeleteModel(
                    name='LoadSheddingStage',
                ),
                migrations.DeleteModel(
                    name='LoadSheddingVersion',
                ),
            ],
        ),
    ]
