# Generated by Django 6.0.2 on 2026-03-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_reset_loadshedding_models'),
    ]

    operations = []
