# Generated by Django 6.0.2 on 2026-03-03 12:20

from django.db import migrations


def rebuild_loadsheddingsetting(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if 'core_loadsheddingsetting' in existing_tables:
        schema_editor.execute("DROP TABLE IF EXISTS core_loadsheddingsetting")

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingsetting ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "scheme_type varchar(10) NOT NULL DEFAULT 'UFLS', "
        "threshold real NOT NULL, "
        "time_delay real NOT NULL, "
        "label varchar(64) NOT NULL DEFAULT ''"
        ")"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_loadsheddingsetting_unique_together'),
    ]

    operations = [
        migrations.RunPython(rebuild_loadsheddingsetting, migrations.RunPython.noop),
    ]
