# Generated by Django 6.0.2 on 2026-03-03 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def rebuild_loadshedding_version_stage(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    tables_to_drop = [
        'core_loadsheddingstagesetting',
        'core_loadsheddingstage',
        'core_loadsheddingversion',
    ]

    for table_name in tables_to_drop:
        if table_name in existing_tables:
            schema_editor.execute(f"DROP TABLE IF EXISTS {table_name}")

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingversion ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "scheme_type varchar(10) NOT NULL, "
        "version_label varchar(50) NOT NULL"
        ")"
    )

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingstage ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "stage_number integer NOT NULL, "
        "label varchar(20) NOT NULL, "
        "version_id char(32) NOT NULL REFERENCES core_loadsheddingversion(id) ON DELETE CASCADE"
        ")"
    )

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingstagesetting ("
        "id integer NOT NULL PRIMARY KEY AUTOINCREMENT, "
        "stage_id char(32) NOT NULL REFERENCES core_loadsheddingstage(id) ON DELETE CASCADE, "
        "setting_id char(32) NOT NULL REFERENCES core_loadsheddingsetting(id) ON DELETE CASCADE, "
        "version_id char(32) NOT NULL REFERENCES core_loadsheddingversion(id) ON DELETE CASCADE"
        ")"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rebuild_loadsheddingsetting_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rebuild_loadshedding_version_stage, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='LoadSheddingVersion',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('scheme_type', models.CharField(choices=[('UFLS', 'UFLS'), ('UVLS', 'UVLS'), ('EMLS', 'EMLS')], max_length=10)),
                        ('version_label', models.CharField(help_text="e.g. '2024-v1', '2025-draft'", max_length=50)),
                    ],
                    options={
                        'ordering': ['version_label'],
                        'verbose_name': 'Load Shedding Version',
                    },
                ),
                migrations.CreateModel(
                    name='LoadSheddingStage',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('stage_number', models.IntegerField()),
                        ('label', models.CharField(blank=True, max_length=20)),
                        ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.loadsheddingversion')),
                    ],
                    options={
                        'ordering': ['stage_number'],
                    },
                ),
                migrations.CreateModel(
                    name='LoadSheddingStageSetting',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loadsheddingsetting')),
                        ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loadsheddingstage')),
                        ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loadsheddingversion')),
                    ],
                    options={
                        'unique_together': {('stage', 'setting'), ('version', 'setting')},
                    },
                ),
                migrations.AddField(
                    model_name='loadsheddingstage',
                    name='settings',
                    field=models.ManyToManyField(blank=True, related_name='stages', through='core.LoadSheddingStageSetting', to='core.loadsheddingsetting'),
                ),
            ],
        ),
    ]
