# Generated by Django 6.0.2 on 2026-03-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_create_loadshedding_version_stage'),
    ]

    operations = []
