# Generated by Django 6.0.2 on 2026-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_loadsheddingsetting_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotransformer',
            options={'ordering': ['substation__substation_id', 'transformer_no'], 'verbose_name': 'Auto Transformer', 'verbose_name_plural': 'Auto Transformers'},
        ),
        migrations.AlterModelOptions(
            name='criticalcategory',
            options={'ordering': ['category_name'], 'verbose_name': 'Critical Category', 'verbose_name_plural': 'Critical Categories'},
        ),
        migrations.AlterModelOptions(
            name='criticalsource',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Critical Source', 'verbose_name_plural': 'Critical Sources'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsnapshotstate',
            options={'verbose_name': 'Equipment Snapshot State', 'verbose_name_plural': 'Equipment Snapshot States'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttopologymap',
            options={'verbose_name': 'Equipment Topology Map', 'verbose_name_plural': 'Equipment Topology Maps'},
        ),
        migrations.AlterModelOptions(
            name='incomingbranch',
            options={'ordering': ['substation__substation_id', 'to_substation__substation_id', 'ckt_id'], 'verbose_name': 'Incoming Branch', 'verbose_name_plural': 'Incoming Branches'},
        ),
        migrations.AlterModelOptions(
            name='incomingbranchalias',
            options={'ordering': ['-effective_from'], 'verbose_name': 'Incoming Branch Alias', 'verbose_name_plural': 'Incoming Branch Aliases'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingrelay',
            options={'ordering': ['id'], 'verbose_name': 'Load Shedding Relay', 'verbose_name_plural': 'Load Shedding Relays'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingsetting',
            options={'ordering': ['scheme_type', 'threshold', 'time_delay'], 'verbose_name': 'Load Shedding Setting', 'verbose_name_plural': 'Load Shedding Settings'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingstage',
            options={'ordering': ['label'], 'verbose_name': 'Load Shedding Stage', 'verbose_name_plural': 'Load Shedding Stages'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingstagesetting',
            options={'verbose_name': 'Load Shedding Stage Setting', 'verbose_name_plural': 'Load Shedding Stage Settings'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingversion',
            options={'ordering': ['version_label'], 'verbose_name': 'Load Shedding Version', 'verbose_name_plural': 'Load Shedding Versions'},
        ),
        migrations.AlterModelOptions(
            name='loadtransformer',
            options={'ordering': ['substation__substation_id', 'transformer_no'], 'verbose_name': 'Load Transformer', 'verbose_name_plural': 'Load Transformers'},
        ),
        migrations.AlterModelOptions(
            name='networkdclink',
            options={'verbose_name': 'Network DC Link', 'verbose_name_plural': 'Network DC Links'},
        ),
        migrations.AlterModelOptions(
            name='networkgenerator',
            options={'verbose_name': 'Network Generator', 'verbose_name_plural': 'Network Generators'},
        ),
        migrations.AlterModelOptions(
            name='networkload',
            options={'verbose_name': 'Network Load', 'verbose_name_plural': 'Network Loads'},
        ),
        migrations.AlterModelOptions(
            name='networkshunt',
            options={'verbose_name': 'Network Shunt', 'verbose_name_plural': 'Network Shunts'},
        ),
        migrations.AlterModelOptions(
            name='networkswitchedshunt',
            options={'verbose_name': 'Network Shunt', 'verbose_name_plural': 'Network Shunts'},
        ),
        migrations.AlterModelOptions(
            name='networktopology',
            options={'ordering': ['created_at'], 'verbose_name': 'Network Topology', 'verbose_name_plural': 'Network Topologies'},
        ),
        migrations.AlterModelOptions(
            name='snapshotbusstate',
            options={'verbose_name': 'Snapshot Bus State', 'verbose_name_plural': 'Snapshot Bus States'},
        ),
        migrations.AlterModelOptions(
            name='topologybranch',
            options={'verbose_name': 'Topology Branch', 'verbose_name_plural': 'Topology Branches'},
        ),
        migrations.AlterModelOptions(
            name='topologybus',
            options={'verbose_name': 'Topology Bus', 'verbose_name_plural': 'Topology Buses'},
        ),
        migrations.AlterModelOptions(
            name='topologytransformer',
            options={'verbose_name': 'Topology Transformer', 'verbose_name_plural': 'Topology Transformers'},
        ),
        migrations.AlterModelOptions(
            name='topologyversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Topology Version', 'verbose_name_plural': 'Topology Versions'},
        ),
        migrations.AddField(
            model_name='networkdclink',
            name='in_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='networkswitchedshunt',
            name='in_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='networkload',
            unique_together={('snapshot', 'bus', 'load_id')},
        ),
        migrations.AddIndex(
            model_name='networkload',
            index=models.Index(fields=['snapshot', 'bus', 'load_id'], name='core_networ_snapsho_237cef_idx'),
        ),
    ]
