# Generated by Django 6.0.2 on 2026-03-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_autotransformer_options_and_more'),
    ]

    operations = []
