# Generated by Django 6.0.2 on 2026-03-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_loadsheddingsetting_unique_together'),
    ]

    operations = []
