# Generated by Django 6.0.1 on 2026-03-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_loadsheddingsetting_unique_together'),
    ]

    operations = []
