# Generated by Django 6.0.2 on 2026-03-03 14:45

from django.db import migrations


def rebuild_loadsheddingstage(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if 'core_loadsheddingstagesetting' in existing_tables:
        schema_editor.execute("DROP TABLE IF EXISTS core_loadsheddingstagesetting")
    if 'core_loadsheddingstage' in existing_tables:
        schema_editor.execute("DROP TABLE IF EXISTS core_loadsheddingstage")

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingstage ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "label varchar(20) NOT NULL, "
        "version_id char(32) NOT NULL REFERENCES core_loadsheddingversion(id) ON DELETE CASCADE"
        ")"
    )

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingstagesetting ("
        "id integer NOT NULL PRIMARY KEY AUTOINCREMENT, "
        "stage_id char(32) NOT NULL REFERENCES core_loadsheddingstage(id) ON DELETE CASCADE, "
        "setting_id char(32) NOT NULL REFERENCES core_loadsheddingsetting(id) ON DELETE CASCADE, "
        "version_id char(32) NOT NULL REFERENCES core_loadsheddingversion(id) ON DELETE CASCADE"
        ")"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_loadsheddingsetting_unique_together'),
    ]

    operations = [
        migrations.RunPython(rebuild_loadsheddingstage, migrations.RunPython.noop),
    ]
