# Generated by Django 6.0.2 on 2026-03-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_rebuild_loadsheddingstage_table'),
    ]

    operations = []
