# Generated by Django 6.0.2 on 2026-03-03 14:55

from django.db import migrations


def add_stage_number(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if 'core_loadsheddingstage' not in existing_tables:
        return

    schema_editor.execute(
        "ALTER TABLE core_loadsheddingstage "
        "ADD COLUMN stage_number integer NOT NULL DEFAULT 1"
    )

    schema_editor.execute(
        "UPDATE core_loadsheddingstage "
        "SET label = 'Stage ' || stage_number "
        "WHERE label IS NULL OR label = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_loadsheddingsetting_unique_together'),
    ]

    operations = [
        migrations.RunPython(add_stage_number, migrations.RunPython.noop),
    ]
