# Generated by Django 6.0.2 on 2026-03-03 15:05

from django.db import migrations


def rebuild_loadsheddingversion_full(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    tables_to_drop = [
        'core_loadsheddingstagesetting',
        'core_loadsheddingstage',
    ]

    for table_name in tables_to_drop:
        if table_name in existing_tables:
            schema_editor.execute(f"DROP TABLE IF EXISTS {table_name}")

    if 'core_loadsheddingversion' in existing_tables:
        schema_editor.execute(
            "CREATE TABLE core_loadsheddingversion_backup AS "
            "SELECT id, scheme_type, version_label FROM core_loadsheddingversion"
        )
        schema_editor.execute("DROP TABLE IF EXISTS core_loadsheddingversion")

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingversion ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "scheme_type varchar(10) NOT NULL, "
        "version_label varchar(50) NOT NULL, "
        "status varchar(20) NOT NULL DEFAULT 'draft', "
        "is_active bool NOT NULL DEFAULT 0, "
        "published_at datetime NULL, "
        "published_by_id integer NULL, "
        "created_at datetime NOT NULL, "
        "updated_at datetime NOT NULL, "
        "notes text NOT NULL DEFAULT ''"
        ")"
    )

    if 'core_loadsheddingversion_backup' in schema_editor.connection.introspection.table_names():
        schema_editor.execute(
            "INSERT INTO core_loadsheddingversion "
            "(id, scheme_type, version_label, status, is_active, published_at, published_by_id, created_at, updated_at, notes) "
            "SELECT id, scheme_type, version_label, 'draft', 0, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '' "
            "FROM core_loadsheddingversion_backup"
        )
        schema_editor.execute("DROP TABLE IF EXISTS core_loadsheddingversion_backup")

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingstage ("
        "id char(32) NOT NULL PRIMARY KEY, "
        "stage_number integer NOT NULL, "
        "label varchar(20) NOT NULL, "
        "version_id char(32) NOT NULL REFERENCES core_loadsheddingversion(id) ON DELETE CASCADE"
        ")"
    )

    schema_editor.execute(
        "CREATE TABLE core_loadsheddingstagesetting ("
        "id integer NOT NULL PRIMARY KEY AUTOINCREMENT, "
        "stage_id char(32) NOT NULL REFERENCES core_loadsheddingstage(id) ON DELETE CASCADE, "
        "setting_id char(32) NOT NULL REFERENCES core_loadsheddingsetting(id) ON DELETE CASCADE, "
        "version_id char(32) NOT NULL REFERENCES core_loadsheddingversion(id) ON DELETE CASCADE"
        ")"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_stage_number_to_loadsheddingstage'),
    ]

    operations = [
        migrations.RunPython(rebuild_loadsheddingversion_full, migrations.RunPython.noop),
    ]
