# Generated by Django 6.0.2 on 2026-03-04 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_rebuild_loadsheddingversion_full'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='loadsheddingstage',
                    options={'ordering': ['version', 'stage_number'], 'verbose_name': 'Load Shedding Stage', 'verbose_name_plural': 'Load Shedding Stages'},
                ),
                migrations.AlterModelOptions(
                    name='loadsheddingstagesetting',
                    options={},
                ),
                migrations.AlterModelOptions(
                    name='loadsheddingversion',
                    options={'ordering': ['-created_at'], 'verbose_name': 'Load Shedding Version', 'verbose_name_plural': 'Load Shedding Versions'},
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='is_active',
                    field=models.BooleanField(default=False, help_text='Whether this is the currently enforced version'),
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='notes',
                    field=models.TextField(blank=True, help_text='Change notes between versions'),
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='published_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='published_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_load_shedding_versions', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='status',
                    field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
                ),
                migrations.AddField(
                    model_name='loadsheddingversion',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name='loadsheddingsetting',
                    name='label',
                    field=models.CharField(blank=True, max_length=64),
                ),
                migrations.AlterField(
                    model_name='loadsheddingstage',
                    name='settings',
                    field=models.ManyToManyField(related_name='stages', through='core.LoadSheddingStageSetting', to='core.loadsheddingsetting'),
                ),
            ],
        ),
    ]
