# Generated by Django 6.0.2 on 2026-03-04 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_loadshedding_transformer_bay_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if 'core_loadsheddingtransformerbay' not in existing_tables:
        schema_editor.execute(
            "CREATE TABLE core_loadsheddingtransformerbay ("
            "id char(32) NOT NULL PRIMARY KEY, "
            "mw_cache text NULL, "
            "stage_id char(32) NOT NULL REFERENCES core_loadsheddingstage(id) ON DELETE CASCADE, "
            "relay_id char(32) NOT NULL REFERENCES core_loadsheddingrelay(id) ON DELETE CASCADE"
            ")"
        )

    if 'core_loadsheddingtransformerbay_transformers' not in existing_tables:
        schema_editor.execute(
            "CREATE TABLE core_loadsheddingtransformerbay_transformers ("
            "id integer NOT NULL PRIMARY KEY AUTOINCREMENT, "
            "loadsheddingtransformerbay_id char(32) NOT NULL REFERENCES core_loadsheddingtransformerbay(id) ON DELETE CASCADE, "
            "loadtransformer_id integer NOT NULL REFERENCES core_loadtransformer(id) ON DELETE CASCADE"
            ")"
        )


def create_loadshedding_setting_unique(schema_editor):
    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uniq_loadshedding_setting_trip "
        "ON core_loadsheddingsetting (scheme_type, threshold, time_delay)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_loadsheddingsetting_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_loadshedding_transformer_bay_tables, migrations.RunPython.noop),
                migrations.RunPython(lambda apps, schema_editor: create_loadshedding_setting_unique(schema_editor), migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='LoadSheddingTransformerBay',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('mw_cache', models.JSONField(blank=True, help_text='{"snapshot_id": "...", "mw": 18.4, "computed_at": "..."}', null=True)),
                        ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_transformer_bays', to='core.loadsheddingrelay')),
                        ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformer_bays', to='core.loadsheddingstage')),
                        ('transformers', models.ManyToManyField(related_name='load_shedding_transformer_bays', to='core.loadtransformer')),
                    ],
                ),
                migrations.AddConstraint(
                    model_name='loadsheddingsetting',
                    constraint=models.UniqueConstraint(fields=('scheme_type', 'threshold', 'time_delay'), name='uniq_loadshedding_setting_trip'),
                ),
            ],
        ),
    ]
