# Generated by Django 6.0.1 on 2026-03-04 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def deduplicate_relays(apps, schema_editor):
    """
    Merge duplicate relays for the same substation before enforcing uniqueness.
    Keep the relay with the most related objects (transformers/branches).
    All bays pointing to removed relays are reassigned to the keeper.
    """
    LoadSheddingRelay = apps.get_model('core', 'LoadSheddingRelay')
    LoadSheddingTransformerBay = apps.get_model('core', 'LoadSheddingTransformerBay')

    from django.db.models import Count
    dupes = (
        LoadSheddingRelay.objects
        .values('substation_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )
    for dup in dupes:
        substation_id = dup['substation_id']
        relays = list(
            LoadSheddingRelay.objects
            .filter(substation_id=substation_id)
            .order_by('id')
        )
        # Keep the first one (oldest by id sort), delete the rest
        keeper = relays[0]
        for extra in relays[1:]:
            # Reassign any transformer bays pointing at the extra relay
            LoadSheddingTransformerBay.objects.filter(relay=extra).update(relay=keeper)
            # Copy any M2M relations (load_transformers, incoming_branches, auto_transformers)
            for lt in extra.load_transformers.all():
                keeper.load_transformers.add(lt)
            for ib in extra.incoming_branches.all():
                keeper.incoming_branches.add(ib)
            for at in extra.auto_transformers.all():
                keeper.auto_transformers.add(at)
            extra.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_add_transformer_bay_and_setting_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheddingPocketBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topology_cache', models.JSONField(blank=True, help_text='{"snapshot_id": "...", "isolated_substations": [], "mw": 34.7, "computed_at": "..."}', null=True)),
                ('topology_valid', models.BooleanField(default=True)),
                ('topology_alert', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Load Shedding Pocket Bay',
                'verbose_name_plural': 'Load Shedding Pocket Bays',
            },
        ),
        migrations.CreateModel(
            name='LoadSheddingSpurBay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topology_cache', models.JSONField(blank=True, help_text='{"snapshot_id": "...", "isolated_substations": [], "mw": 12.1, "computed_at": "..."}', null=True)),
            ],
            options={
                'verbose_name': 'Load Shedding Spur Bay',
                'verbose_name_plural': 'Load Shedding Spur Bays',
            },
        ),
        migrations.AlterModelOptions(
            name='loadsheddingrelay',
            options={'ordering': ['substation__substation_id'], 'verbose_name': 'Load Shedding Relay', 'verbose_name_plural': 'Load Shedding Relays'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingstagesetting',
            options={'verbose_name': 'Load Shedding Stage Setting', 'verbose_name_plural': 'Load Shedding Stage Settings'},
        ),
        migrations.AlterModelOptions(
            name='loadsheddingtransformerbay',
            options={'verbose_name': 'Load Shedding Transformer Bay', 'verbose_name_plural': 'Load Shedding Transformer Bays'},
        ),
        # The old LoadSheddingSetting had unique_together = ('stage', 'order') in migration
        # state only (prior migrations used SeparateDatabaseAndState). Those fields never
        # existed in the actual DB, so we clear the state-level constraint without touching DB.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='loadsheddingsetting',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='loadsheddingstage',
            name='settings',
            field=models.ManyToManyField(blank=True, related_name='stages', through='core.LoadSheddingStageSetting', to='core.loadsheddingsetting'),
        ),
        migrations.AlterUniqueTogether(
            name='loadsheddingtransformerbay',
            unique_together={('stage', 'relay')},
        ),
        migrations.RunPython(deduplicate_relays, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='loadsheddingrelay',
            constraint=models.UniqueConstraint(fields=('substation',), name='uniq_one_relay_per_substation'),
        ),
        migrations.AddConstraint(
            model_name='loadsheddingversion',
            constraint=models.UniqueConstraint(fields=('scheme_type', 'version_label'), name='uniq_version_per_scheme_type'),
        ),
        migrations.AddField(
            model_name='loadsheddingpocketbay',
            name='boundary_branches',
            field=models.ManyToManyField(related_name='load_shedding_pocket_boundary_bays', to='core.incomingbranch'),
        ),
        migrations.AddField(
            model_name='loadsheddingpocketbay',
            name='boundary_relays',
            field=models.ManyToManyField(related_name='target_pocket_bays', to='core.loadsheddingrelay'),
        ),
        migrations.AddField(
            model_name='loadsheddingpocketbay',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocket_bays', to='core.loadsheddingstage'),
        ),
        migrations.AddField(
            model_name='loadsheddingspurbay',
            name='branches',
            field=models.ManyToManyField(related_name='load_shedding_spur_bays', to='core.incomingbranch'),
        ),
        migrations.AddField(
            model_name='loadsheddingspurbay',
            name='relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_spur_bays', to='core.loadsheddingrelay'),
        ),
        migrations.AddField(
            model_name='loadsheddingspurbay',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spur_bays', to='core.loadsheddingstage'),
        ),
        migrations.AlterUniqueTogether(
            name='loadsheddingspurbay',
            unique_together={('stage', 'relay')},
        ),
    ]
