# Generated by Django 6.0.1 on 2026-03-06 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_load_shedding_audit_fixes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadsheddingpocketbay',
            name='boundary_branches',
        ),
        migrations.RemoveField(
            model_name='loadsheddingpocketbay',
            name='boundary_relays',
        ),
        migrations.CreateModel(
            name='LoadSheddingPocketBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branches', models.ManyToManyField(related_name='load_shedding_pocket_boundaries', to='core.incomingbranch')),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='core.loadsheddingpocketbay')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_pocket_boundaries', to='core.loadsheddingrelay')),
            ],
            options={
                'verbose_name': 'Load Shedding Pocket Boundary',
                'verbose_name_plural': 'Load Shedding Pocket Boundaries',
            },
        ),
    ]
