# Generated by Django 6.0.1 on 2026-03-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_loadsheddingpocketbay_boundary_branches_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadSheddingSpurBay',
        ),
    ]
