# Generated by Django 6.0.1 on 2026-03-06 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_delete_loadsheddingspurbay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadsheddingversion',
            options={'ordering': ['-review_year', '-version'], 'verbose_name': 'Load Shedding Version', 'verbose_name_plural': 'Load Shedding Versions'},
        ),
        migrations.RemoveConstraint(
            model_name='loadsheddingversion',
            name='uniq_version_per_scheme_type',
        ),
        migrations.AddField(
            model_name='loadsheddingversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_load_shedding_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadsheddingversion',
            name='review_year',
            field=models.IntegerField(default=2024, help_text='The year this version is for (e.g. 2024)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadsheddingversion',
            name='version',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadsheddingversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loadsheddingversion',
            constraint=models.UniqueConstraint(fields=('scheme_type', 'review_year', 'version'), name='uniq_version_per_year_scheme'),
        ),
        migrations.RemoveField(
            model_name='loadsheddingversion',
            name='version_label',
        ),
    ]
