# Generated by Django 6.0.1 on 2026-03-07 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_loadsheddingversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loadsheddingsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadsheddingsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
