# Generated by Django 6.0.1 on 2026-03-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_loadsheddingrelay_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loadsheddingrelay',
            name='uniq_one_relay_per_substation',
        ),
    ]
