# Generated by Django 6.0.1 on 2026-03-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_loadsheddingrelay_uniq_one_relay_per_substation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='relay_name',
            field=models.CharField(blank=True, help_text='Optional name to distinguish multiple relays at the same site', max_length=100),
        ),
    ]
