# Generated by Django 6.0.2 on 2026-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_loadsheddingrelay_relay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substation',
            name='ownership',
            field=models.CharField(choices=[('TNB', 'Tenaga Nasional Berhad (TNB)'), ('DC', 'Data Centre (DC)'), ('LSS', 'Large Scale Solar (LSS)'), ('IPP', 'Independent Power Producer (IPP)'), ('LPC', 'Large Power Consumer (LPC)'), ('Tie-Line', 'Tie-Line')], default='TNB', max_length=50),
        ),
        migrations.AlterField(
            model_name='substation',
            name='voltage',
            field=models.IntegerField(choices=[(500, '500 kV'), (275, '275 kV'), (230, '230 kV'), (132, '132 kV')]),
        ),
    ]
