# Generated by Django 6.0.1 on 2026-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_substation_ownership_alter_substation_voltage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadsheddingsetting',
            options={'ordering': ['-threshold', 'time_delay'], 'verbose_name': 'Load Shedding Setting', 'verbose_name_plural': 'Load Shedding Settings'},
        ),
        migrations.AddField(
            model_name='loadsheddingstage',
            name='target_mw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='loadsheddingstage',
            constraint=models.UniqueConstraint(fields=('version', 'stage_number'), name='uniq_stage_per_version'),
        ),
    ]
