# Generated by Django 6.0.1 on 2026-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_loadsheddingsetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheddingversion',
            name='target_percentage',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='The target load shedding percentage goal (e.g. 60.00)', max_digits=5),
        ),
    ]
