# Generated by Django 6.0.1 on 2026-04-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_loadsheddingversion_target_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadsheddingstagesetting',
            options={'ordering': ['order'], 'verbose_name': 'Load Shedding Stage Setting', 'verbose_name_plural': 'Load Shedding Stage Settings'},
        ),
        migrations.AddField(
            model_name='loadsheddingstagesetting',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
