# Generated by Django 6.0.1 on 2026-04-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_loadsheddingstagesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheddingpocketboundary',
            name='frozen_assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loadsheddingpocketboundary',
            name='frozen_relay_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='loadsheddingpocketboundary',
            name='frozen_substation_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loadsheddingpocketboundary',
            name='frozen_substation_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='loadsheddingtransformerbay',
            name='frozen_assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loadsheddingtransformerbay',
            name='frozen_relay_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='loadsheddingtransformerbay',
            name='frozen_substation_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loadsheddingtransformerbay',
            name='frozen_substation_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='loadsheddingpocketboundary',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='load_shedding_pocket_boundaries', to='core.incomingbranch'),
        ),
        migrations.AlterField(
            model_name='loadsheddingpocketboundary',
            name='relay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_pocket_boundaries', to='core.loadsheddingrelay'),
        ),
        migrations.AlterField(
            model_name='loadsheddingtransformerbay',
            name='relay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_transformer_bays', to='core.loadsheddingrelay'),
        ),
        migrations.AlterField(
            model_name='loadsheddingtransformerbay',
            name='transformers',
            field=models.ManyToManyField(blank=True, related_name='load_shedding_transformer_bays', to='core.loadtransformer'),
        ),
    ]
