# Generated by Django 6.0.2 on 2026-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_loadsheddingpocketboundary_frozen_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheddingrelay',
            name='target_voltage',
            field=models.IntegerField(blank=True, help_text="Target voltage level in kV for this relay's breaker trip assignments", null=True),
        ),
    ]
