# Generated by Django 6.0.2 on 2026-04-17 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_target_voltage_to_loadsheddingrelay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheddingAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_type', models.CharField(choices=[('UFLS', 'UFLS'), ('UVLS', 'UVLS'), ('EMLS', 'EMLS')], max_length=10, unique=True)),
                ('ufls_protected_stages', models.JSONField(default=list, help_text='Stage numbers in the active UFLS version that may not overlap with other scheme types.')),
                ('critical_restricted_stages', models.JSONField(default=list, help_text='Stage numbers where critical substations must not be assigned.')),
                ('enforcement_mode', models.CharField(choices=[('warn', 'Warn only'), ('block', 'Block assignment')], default='warn', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Load Shedding Alert Config',
                'verbose_name_plural': 'Load Shedding Alert Configs',
            },
        ),
    ]
