# Generated by Django 6.0.2 on 2026-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_loadsheddingalertconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadsheddingalertconfig',
            name='enforcement_mode',
        ),
        migrations.AddField(
            model_name='loadsheddingalertconfig',
            name='rule1_enforcement',
            field=models.CharField(choices=[('warn', 'Warn only'), ('block', 'Block assignment')], default='warn', help_text='Enforcement mode for Rule 1 (no cross-scheme overlap).', max_length=10),
        ),
        migrations.AddField(
            model_name='loadsheddingalertconfig',
            name='rule2_enforcement',
            field=models.CharField(choices=[('warn', 'Warn only'), ('block', 'Block assignment')], default='warn', help_text='Enforcement mode for Rule 2 (critical substation in restricted stages).', max_length=10),
        ),
    ]
