# Generated by Django 6.0.1 on 2026-04-29 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_per_rule_enforcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheddingChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('new', 'New Assignment'), ('revised', 'Revised'), ('defeated', 'Defeated')], max_length=20)),
                ('substation_id', models.CharField(blank=True, max_length=50)),
                ('substation_name', models.CharField(blank=True, max_length=150)),
                ('feeder', models.CharField(blank=True, max_length=200)),
                ('old_stage_label', models.CharField(blank=True, max_length=100)),
                ('new_stage_label', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('compared_to_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compared_in_logs', to='core.loadsheddingversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_change_logs', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_change_logs', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.loadsheddingversion')),
            ],
            options={
                'verbose_name': 'Load Shedding Change Log',
                'verbose_name_plural': 'Load Shedding Change Logs',
                'ordering': ['change_type', 'substation_id'],
            },
        ),
    ]
