# Generated by Django 6.0.1 on 2026-05-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_loadsheddingchangelog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkowner',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='networkowner',
            name='snapshot',
        ),
        migrations.AlterUniqueTogether(
            name='networkzone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='networkzone',
            name='snapshot',
        ),
        migrations.DeleteModel(
            name='NetworkArea',
        ),
        migrations.DeleteModel(
            name='NetworkOwner',
        ),
        migrations.DeleteModel(
            name='NetworkZone',
        ),
    ]
